version: '3'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${BRANCH}.vps704954.ovh.net
      - "traefik.port=80"
    networks:
      - web
networks:
  web:
    external:
      name: web
